services:
  trabalho1-angular:
    image: devops/trabalho1-angular:latest
    container_name: trabalho1-angular
    build:
      context: ../../angular/
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - abp-network
    depends_on:
      - trabalho1-authserver
      - trabalho1-api

  trabalho1-api:
    image: devops/trabalho1-api:latest
    container_name: trabalho1-api
    hostname: trabalho1-api
    build:
      context: ../../
      dockerfile: src/Devops.Trabalho1.HttpApi.Host/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=186744b5-efac-4578-8b34-fb823c44ae8a
      - App__SelfUrl=http://trabalho1-api:8080
      - App__AngularUrl=http://localhost:4200
      - App__CorsOrigins=http://trabalho1-authserver:8080,http://localhost:8080 http://trabalho1-angular:80,http://localhost:4200
      - App__HealthCheckUrl=http://trabalho1-api:8080/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://localhost:8080
      - AuthServer__MetaAddress=http://localhost:8080
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=Trabalho1;Pooling=false
      - Redis__Configuration=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    networks:
      - abp-network

  trabalho1-authserver:
    image: devops/trabalho1-authserver:latest
    container_name: trabalho1-authserver
    ports:
      - "8080:8080"  # Expondo a porta HTTP
    build:
      context: ../../
      dockerfile: src/Devops.Trabalho1.AuthServer/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - App__SelfUrl=http://localhost:8080
      - App__CorsOrigins=http://trabalho1-angular:80,http://trabalho1-api:8080,http://localhost:4200
      - App__HealthCheckUrl=http://trabalho1-authserver:8080/health-status
      - App__AngularUrl=http://localhost:4200
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://localhost:8080
      - Kestrel__Certificates__Default__Path=/app/certs/localhost.pfx
      - Kestrel__Certificates__Default__Password=186744b5-efac-4578-8b34-fb823c44ae8a
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=Trabalho1;Pooling=false
      - Redis__Configuration=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    networks:
      - abp-network

  db-migrator:
    image: devops/trabalho1-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Devops.Trabalho1.DbMigrator/Dockerfile
    environment:
      - OpenIddict__Applications__Trabalho1_App__RootUrl=http://localhost:4200
      - OpenIddict__Applications__Trabalho1_Swagger__RootUrl=http://trabalho1-api:8080
      - ConnectionStrings__Default=User ID=postgres;Password=myPassw0rd;Host=postgres;Port=5432;Database=Trabalho1;Pooling=false
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - abp-network

  postgres:
    container_name: postgres-db
    image: postgres:14.1
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "myPassw0rd"
    volumes:
      - postgres_data:/var/opt/postgres
    networks:
      - abp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - abp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

volumes:
  postgres_data:
    name: trabalho1_postgres_data

networks:
  abp-network:
    name: trabalho1-network
    driver: bridge

