{{- range .Values.apps }}
{{- if and .enabled .service.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .service.name }}
  labels:
    app: {{ .name }}
spec:
  type: {{ .service.type }}
  selector:
    app: trabalho1-{{ .name }}
  ports:
    {{- range .service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
{{- end }}
{{- end }}
