apiVersion: v1
kind: Service
metadata:
  name: trabalho1-api
spec:
  selector:
    app: trabalho1-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
