apiVersion: v1
kind: Service
metadata:
  name: trabalho1-authserver
spec:
  selector:
    app: trabalho1-authserver
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP